/*
 * Copyright (c) 2024, Haiyang Li.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.landawn.abacus.jdbc;

/**
 * Internal constants container providing the standardized parameter-name string literals
 * used by argument-validation calls (e.g., {@code N.checkArgNotNull(handler, cs.handler)})
 * throughout the Abacus JDBC framework.
 *
 * <p>This utility class centralizes the textual identifiers that appear in error messages
 * and diagnostics, ensuring that the parameter name reported when a validation fails
 * matches the actual method-parameter name in the source code, and reducing the risk
 * of typos when the same name is referenced across many call sites.</p>
 *
 * <p><b>Contract:</b> each constant's name and its string value are identical, and both must equal
 * the declared name of the method parameter it validates. Renaming a method parameter therefore
 * requires renaming the corresponding constant (and its value) in the same change, and vice versa,
 * so the three names never drift apart.</p>
 *
 * <p>The constants are primarily used in:</p>
 * <ul>
 *   <li>{@code N.checkArgNotNull / checkArgNotEmpty / ...} validation calls inside framework methods</li>
 *   <li>Argument labels for exception messages thrown by framework methods</li>
 *   <li>Internal logging and diagnostic output</li>
 * </ul>
 *
 * <p><b>Usage Example (framework-internal):</b></p>
 * <pre>{@code
 * void register(final Class<?> daoInterface, final Jdbc.Handler<?> handler) {
 *     N.checkArgNotNull(daoInterface, cs.daoInterface);
 *     N.checkArgNotNull(handler, cs.handler);
 *     // ...
 * }
 * }</pre>
 */
public final class cs { // NOSONAR
    /**
     * Private constructor to prevent instantiation of this utility class.
     */
    private cs() {
        // utility class - prevent instantiation
    }

    /**
     * Parameter name for action callbacks and operations.
     */
    public static final String action = "action";
    /**
     * Parameter name for actions to be executed after method invocation.
     */
    public static final String afterInvokeAction = "afterInvokeAction";
    /**
     * Parameter name for extractors that retrieve auto-generated keys from insert operations.
     */
    public static final String autoGeneratedKeyExtractor = "autoGeneratedKeyExtractor";
    /**
     * Parameter name for collections of parameters used in batch operations.
     */
    public static final String batchParameters = "batchParameters";
    /**
     * Parameter name for the size of batches in batch processing operations.
     */
    public static final String batchSize = "batchSize";
    /**
     * Parameter name for actions to be executed before method invocation.
     */
    public static final String beforeInvokeAction = "beforeInvokeAction";
    /**
     * Parameter name for handlers responsible for resource cleanup and closing operations.
     */
    public static final String closeHandler = "closeHandler";
    /**
     * Parameter name for command objects or command specifications.
     */
    public static final String cmd = "cmd";
    /**
     * Parameter name for functions that extract values from database columns.
     */
    public static final String columnGetter = "columnGetter";
    /**
     * Parameter name for one-based column index in result sets.
     */
    public static final String columnIndex = "columnIndex";
    /**
     * Parameter name for database column names.
     */
    public static final String columnName = "columnName";
    /**
     * Parameter name for a result-set column label (the JDBC label, which falls back to the column name).
     */
    public static final String columnLabel = "columnLabel";
    /**
     * Parameter name for condition objects used in query filtering.
     */
    public static final String cond = "cond";
    /**
     * Parameter name for database Connection objects.
     */
    public static final String conn = "conn";
    /**
     * Parameter name for Consumer functional interfaces that process single elements.
     */
    public static final String consumer = "consumer";
    /**
     * Parameter name for a single consumer applied to every column in a row.
     */
    public static final String consumerForAll = "consumerForAll";
    /**
     * Parameter name for count values or counting operations.
     */
    public static final String count = "count";
    /**
     * Parameter name for Data Access Object interface classes.
     */
    public static final String daoInterface = "daoInterface";
    /**
     * Parameter name for default column value extraction functions.
     */
    public static final String defaultColumnGetter = "defaultColumnGetter";
    /**
     * Parameter name for downstream collectors or operations in stream processing.
     */
    public static final String downstream = "downstream";
    /**
     * Parameter name for the JDBC driver class.
     */
    public static final String driverClass = "driverClass";
    /**
     * Parameter name for DataSource objects used to obtain database connections.
     */
    public static final String ds = "ds";
    /**
     * Parameter name for entity objects representing database records or domain models.
     */
    public static final String entity = "entity";
    /**
     * Parameter name for Class objects representing entity types.
     */
    public static final String entityClass = "entityClass";
    /**
     * Parameter name for Class objects used to create the entity-aware Dataset extractor.
     */
    public static final String entityClassForExtractor = "entityClassForExtractor";
    /**
     * Parameter name for Executor objects used for asynchronous task execution.
     */
    public static final String executor = "executor";
    /**
     * Parameter name for predicates used to filter elements (retaining those that match).
     */
    public static final String filter = "filter";
    /**
     * Parameter name for functions that finish a mapping or collection operation.
     */
    public static final String finisher = "finisher";
    /**
     * Parameter name for function objects or functional interfaces.
     */
    public static final String func = "func";
    /**
     * Parameter name for handler objects that process events or manage operations.
     */
    public static final String handler = "handler";
    /**
     * Parameter name for Class objects representing handler types.
     */
    public static final String handlerClass = "handlerClass";
    /**
     * Parameter name for functions that extract unique identifier values from entities.
     */
    public static final String idExtractor = "idExtractor";
    /**
     * Parameter name for the single property name used to identify entities to merge.
     */
    public static final String idPropNameForMerge = "idPropNameForMerge";
    /**
     * Parameter name for the property names forming the composite key used to identify entities to merge.
     */
    public static final String idPropNamesForMerge = "idPropNamesForMerge";
    /**
     * Parameter name for predicates that test whether an ID value is the default/unset value.
     */
    public static final String isDefaultIdTester = "isDefaultIdTester";
    /**
     * Parameter name for database transaction isolation level settings.
     */
    public static final String isolationLevel = "isolationLevel";
    /**
     * Parameter name for functions that extract key values for grouping or mapping operations.
     */
    public static final String keyExtractor = "keyExtractor";
    /**
     * Parameter name for the thread-local DAO cache opened on the current thread.
     */
    public static final String localThreadCache = "localThreadCache";
    /**
     * Parameter name for binary functions that merge duplicate values in map operations.
     */
    public static final String mergeFunction = "mergeFunction";
    /**
     * Parameter name for suppliers that create multimap instances for collecting grouped values.
     */
    public static final String multimapSupplier = "multimapSupplier";
    /**
     * Parameter name for numeric values, typically representing count, limit, or size.
     */
    public static final String n = "n";
    /**
     * Parameter name for SQL queries that use named parameters instead of positional parameters.
     */
    public static final String namedSql = "namedSql";
    /**
     * Parameter name for offset values used in pagination and result limiting.
     */
    public static final String offset = "offset";
    /**
     * Parameter name for alternative actions to execute when the primary action cannot be performed.
     */
    public static final String orElseAction = "orElseAction";
    /**
     * Parameter name for collections of parameter names used in named SQL queries.
     */
    public static final String parameterNames = "parameterNames";
    /**
     * Parameter name for the subset of named parameters selected to be bound from an entity.
     */
    public static final String parameterNamesToSet = "parameterNamesToSet";
    /**
     * Parameter name for collections of parameter values used in SQL query execution.
     */
    public static final String parameters = "parameters";
    /**
     * Parameter name for functions that set parameters on statements during data transfer.
     */
    public static final String parameterSetter = "parameterSetter";
    /**
     * Parameter name for functions that set multiple parameters on PreparedStatement objects.
     */
    public static final String parametersSetter = "parametersSetter";
    /**
     * Parameter name for collections of property names that should be refreshed after database operations.
     */
    public static final String propNamesToRefresh = "propNamesToRefresh";
    /**
     * Parameter name for qualifier strings used as a unique key to identify or categorize a registered object.
     */
    public static final String qualifier = "qualifier";
    /**
     * Parameter name for the {@code ParametersSetter} that registers OUT parameters of a callable statement.
     */
    public static final String registrar = "registrar";
    /**
     * Parameter name for functions that extract results from ResultSet objects.
     */
    public static final String resultExtractor = "resultExtractor";
    /**
     * Parameter name for the first result extractor function in multi-extractor operations.
     */
    public static final String resultExtractor1 = "resultExtractor1";
    /**
     * Parameter name for the second result extractor function in multi-extractor operations.
     */
    public static final String resultExtractor2 = "resultExtractor2";
    /**
     * Parameter name for the third result extractor function in multi-extractor operations.
     */
    public static final String resultExtractor3 = "resultExtractor3";
    /**
     * Parameter name for arrays of column indexes to be returned from insert operations.
     */
    public static final String generatedKeyColumnIndexes = "generatedKeyColumnIndexes";
    /**
     * Parameter name for arrays of column names to be returned from insert operations.
     */
    public static final String generatedKeyColumnNames = "generatedKeyColumnNames";
    /**
     * Parameter name for consumer functions that process individual rows from result sets.
     */
    public static final String rowConsumer = "rowConsumer";
    /**
     * Parameter name for functions that extract complete row data from ResultSet objects.
     */
    public static final String rowExtractor = "rowExtractor";
    /**
     * Parameter name for predicates that filter rows during result set processing.
     */
    public static final String rowFilter = "rowFilter";
    /**
     * Parameter name for functions that map ResultSet rows to domain objects.
     */
    public static final String rowMapper = "rowMapper";
    /**
     * Parameter name for the first row mapper function in multi-mapper operations.
     */
    public static final String rowMapper1 = "rowMapper1";
    /**
     * Parameter name for the second row mapper function in multi-mapper operations.
     */
    public static final String rowMapper2 = "rowMapper2";
    /**
     * Parameter name for the third row mapper function in multi-mapper operations.
     */
    public static final String rowMapper3 = "rowMapper3";
    /**
     * Parameter name for ResultSet objects in query processing.
     */
    public static final String rs = "rs";
    /**
     * Parameter name for SQL query strings.
     */
    public static final String sql = "sql";
    /**
     * Parameter name for action functions that operate on SQL query results.
     */
    public static final String sqlAction = "sqlAction";
    /**
     * Parameter name for the first SQL action function in multi-action operations.
     */
    public static final String sqlAction1 = "sqlAction1";
    /**
     * Parameter name for the second SQL action function in multi-action operations.
     */
    public static final String sqlAction2 = "sqlAction2";
    /**
     * Parameter name for the third SQL action function in multi-action operations.
     */
    public static final String sqlAction3 = "sqlAction3";
    /**
     * Parameter name for the SQL dialect used to generate a DAO's CRUD SQL.
     */
    public static final String sqlDialect = "sqlDialect";
    /**
     * Parameter name for functions that extract SQL text from statements.
     */
    public static final String sqlExtractor = "sqlExtractor";
    /**
     * Parameter name for handlers that process SQL log events.
     */
    public static final String sqlLogHandler = "sqlLogHandler";
    /**
     * Parameter name for Statement or PreparedStatement objects.
     */
    public static final String stmt = "stmt";
    /**
     * Parameter name for functions that create Statement or PreparedStatement objects.
     */
    public static final String stmtCreator = "stmtCreator";
    /**
     * Parameter name for functions that configure Statement or PreparedStatement objects.
     */
    public static final String stmtSetter = "stmtSetter";
    /**
     * Parameter name for supplier functions that provide objects or values on demand.
     */
    public static final String supplier = "supplier";
    /**
     * Parameter name for Class objects representing target types for mapping or conversion operations.
     */
    public static final String targetClass = "targetClass";
    /**
     * Parameter name for Type objects representing target types for generic operations.
     */
    public static final String targetType = "targetType";
    /**
     * Parameter name for type specifications or Type objects.
     */
    public static final String type = "type";
    /**
     * Parameter name for the property names used to match an existing record (e.g., in upsert operations).
     */
    public static final String matchPropNames = "matchPropNames";
    /**
     * Parameter name for URL strings, typically database connection URLs.
     */
    public static final String url = "url";
    /**
     * Parameter name for functions that extract values from objects or result sets.
     */
    public static final String valueExtractor = "valueExtractor";
    /**
     * Parameter name for a single property name to select in a query.
     */
    public static final String selectPropName = "selectPropName";
    /**
     * Parameter name for specifying the target value type in mapping or conversion operations.
     */
    public static final String targetValueType = "targetValueType";
    /**
     * Parameter name for identifier fields or properties.
     */
    public static final String id = "id";
    /**
     * Parameter name for collections of property names to include in insert operations.
     */
    public static final String propNamesToInsert = "propNamesToInsert";
    /**
     * Parameter name for collections of property names to include in save operations.
     */
    public static final String propNamesToSave = "propNamesToSave";
    /**
     * Parameter name for collections of property names to include in update operations.
     */
    public static final String propNamesToUpdate = "propNamesToUpdate";
    /**
     * Parameter name for property values to update, typically a map from property name to its new value, used by update operations to provide partial updates.
     */
    public static final String propsToUpdate = "propsToUpdate";
    /**
     * Parameter name for named insert SQL statements.
     */
    public static final String namedInsertSql = "namedInsertSql";
    /**
     * Parameter name for join entity property names used in join operations.
     */
    public static final String joinEntityPropName = "joinEntityPropName";
    /**
     * Parameter name for {@link FetchDirection} values passed to statement-configuration methods.
     */
    public static final String direction = "direction";
    /**
     * Parameter name for the one-based parameter index of a callable-statement OUT parameter.
     */
    public static final String parameterIndex = "parameterIndex";
    /**
     * Parameter name for {@code java.sql.SQLType} values used when registering OUT parameters.
     */
    public static final String sqlType = "sqlType";
    /**
     * Parameter name for a single column getter applied to every column in a row.
     */
    public static final String columnGetterForAll = "columnGetterForAll";
    /**
     * Parameter name for the function composed after another in {@code andThen} operations.
     */
    public static final String after = "after";
    /**
     * Parameter name for the other function combined in {@code and}/{@code or} operations.
     */
    public static final String other = "other";
    /**
     * Parameter name for bi-predicates that filter entries (column label and value) before they are placed into the result map.
     */
    public static final String entryFilter = "entryFilter";
    /**
     * Parameter name for suppliers that create map instances for collecting results.
     */
    public static final String mapSupplier = "mapSupplier";
    /**
     * Parameter name for functions that convert column labels into map keys.
     */
    public static final String columnNameConverter = "columnNameConverter";
    /**
     * Parameter name for Class objects (camelCase {@code cls} form).
     */
    public static final String cls = "cls";
    /**
     * Parameter name for {@link java.nio.charset.Charset} values.
     */
    public static final String charset = "charset";
    /**
     * Parameter name for SQL query strings used by paging/streaming helpers.
     */
    public static final String query = "query";
    /**
     * Parameter name for the page size used in paginated query execution.
     */
    public static final String pageSize = "pageSize";
    /**
     * Parameter name for the DDL schema/script used to create a table.
     */
    public static final String schema = "schema";
    /**
     * Parameter name for database table names.
     */
    public static final String tableName = "tableName";
    /**
     * Parameter name for {@link com.landawn.abacus.util.Dataset} objects to be imported or exported.
     */
    public static final String dataset = "dataset";
    /**
     * Parameter name for the action executed after a transaction is committed.
     */
    public static final String actionAfterCommit = "actionAfterCommit";
    /**
     * Parameter name for the action executed after a transaction is rolled back.
     */
    public static final String actionAfterRollback = "actionAfterRollback";
    /**
     * Parameter name for the backing map of a map-based DAO cache.
     */
    public static final String cache = "cache";
    /**
     * Parameter name for the unlock code of a database lock.
     */
    public static final String code = "code";
    /**
     * Parameter name for collections of database column names.
     */
    public static final String columnNames = "columnNames";
    /**
     * Parameter name for the {@code CreatedBy} value identifying which component created a transaction.
     */
    public static final String creator = "creator";
    /**
     * Parameter name for Data Access Object interface classes (alternate {@code daoClass} form).
     */
    public static final String daoClass = "daoClass";
    /**
     * Parameter name for {@link java.time.Duration} delays between batches.
     */
    public static final String delay = "delay";
    /**
     * Parameter name for the SQL builder/DSL used to generate a DAO's SQL.
     */
    public static final String dsl = "dsl";
    /**
     * Parameter name for {@code BeanInfo} descriptors of entity classes.
     */
    public static final String entityInfo = "entityInfo";
    /**
     * Parameter name for the JDBC fetch size applied to a statement or result set.
     */
    public static final String fetchSize = "fetchSize";
    /**
     * Parameter name for {@link java.io.File} objects to read from or write to.
     */
    public static final String file = "file";
    /**
     * Parameter name for the class of the value held by the first column of a row.
     */
    public static final String firstColumnType = "firstColumnType";
    /**
     * Parameter name for the list of ID property names of an entity.
     */
    public static final String idPropNameList = "idPropNameList";
    /**
     * Parameter name for insert SQL statements.
     */
    public static final String insertSql = "insertSql";
    /**
     * Parameter name for the target {@code PreparedStatement} of an insert in a copy operation.
     */
    public static final String insertStmt = "insertStmt";
    /**
     * Parameter name for {@link java.util.Iterator} sources of rows or records.
     */
    public static final String iter = "iter";
    /**
     * Parameter name for the entity class referenced by a join property.
     */
    public static final String joinPropEntityClass = "joinPropEntityClass";
    /**
     * Parameter name for the live time, in milliseconds, of a lock or cache entry.
     */
    public static final String liveTime = "liveTime";
    /**
     * Parameter name for {@link java.util.Map} instances supplied as backing storage.
     */
    public static final String map = "map";
    /**
     * Parameter name for the output sink (file, writer, or stream) of an export operation.
     */
    public static final String output = "output";
    /**
     * Parameter name for the caller-supplied array that receives the values of a row.
     */
    public static final String outputRow = "outputRow";
    /**
     * Parameter name for the name of a named/callable-statement parameter.
     */
    public static final String parameterName = "parameterName";
    /**
     * Parameter name for arrays or lists of parameter values bound to a statement.
     */
    public static final String params = "params";
    /**
     * Parameter name for a single entity property name.
     */
    public static final String propName = "propName";
    /**
     * Parameter name for {@link java.io.Reader} sources of character data.
     */
    public static final String reader = "reader";
    /**
     * Parameter name for the interval, in milliseconds, between lock acquisition retries.
     */
    public static final String retryInterval = "retryInterval";
    /**
     * Parameter name for the select SQL statement of a copy/export operation.
     */
    public static final String selectSql = "selectSql";
    /**
     * Parameter name for the source {@code PreparedStatement} of a select in a copy operation.
     */
    public static final String selectStmt = "selectStmt";
    /**
     * Parameter name for the source database Connection of a copy operation.
     */
    public static final String sourceConn = "sourceConn";
    /**
     * Parameter name for the source DataSource of a copy operation.
     */
    public static final String sourceDataSource = "sourceDataSource";
    /**
     * Parameter name for the source table name of a copy operation.
     */
    public static final String sourceTableName = "sourceTableName";
    /**
     * Parameter name for the one-based index of the first parameter set by a bulk setter.
     */
    public static final String startParameterIndex = "startParameterIndex";
    /**
     * Parameter name for the target identifier of a database lock.
     */
    public static final String target = "target";
    /**
     * Parameter name for timeouts, in milliseconds, of blocking operations.
     */
    public static final String timeout = "timeout";
    /**
     * Parameter name for collections of property values to match.
     */
    public static final String values = "values";
    /**
     * Parameter name for the setter that binds the next page's parameters in paginated DAO queries.
     */
    public static final String paramSetter = "paramSetter";
    /**
     * Parameter name for the map of property names to their new values passed to {@code update} operations.
     */
    public static final String updateProps = "updateProps";
    /**
     * Parameter name for the simple name of the entity class to generate.
     */
    public static final String entityName = "entityName";
    /**
     * Parameter name for the key column used in a generated UPDATE statement's WHERE clause.
     */
    public static final String keyColumnName = "keyColumnName";
    /**
     * Parameter name for the entity class used by a join operation.
     */
    public static final String joinEntityClass = "joinEntityClass";
    /**
     * Parameter name for the property selected by a single-column query.
     */
    public static final String singleSelectPropName = "singleSelectPropName";
    /**
     * Parameter name for the destination data source of a transfer.
     */
    public static final String targetDataSource = "targetDataSource";
    /**
     * Parameter name for the destination connection of a transfer.
     */
    public static final String targetConn = "targetConn";
    /**
     * Parameter name for the destination table of a transfer.
     */
    public static final String targetTableName = "targetTableName";
}
