/*
 * Copyright (c) 2024, Haiyang Li.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.landawn.abacus.jdbc;

public final class s { // NOSONAR
    private s() {
        // singleton
    }

    public static final String ResultSet = "ResultSet";
    public static final String action = "action";
    public static final String afterInvokeAction = "afterInvokeAction";
    public static final String autoGeneratedKeyExtractor = "autoGeneratedKeyExtractor";
    public static final String batchParameters = "batchParameters";
    public static final String batchSize = "batchSize";
    public static final String beforeInvokeAction = "beforeInvokeAction";
    public static final String closeHandler = "closeHandler";
    public static final String cmd = "cmd";
    public static final String columnGetter = "columnGetter";
    public static final String columnIndex = "columnIndex";
    public static final String columnName = "columnName";
    public static final String cond = "cond";
    public static final String conn = "conn";
    public static final String consumer = "consumer";
    public static final String consumerForAll = "consumerForAll";
    public static final String count = "count";
    public static final String daoInterface = "daoInterface";
    public static final String dataSource = "dataSource";
    public static final String defaultColumnGetter = "defaultColumnGetter";
    public static final String downstream = "downstream";
    public static final String entity = "entity";
    public static final String entityClass = "entityClass";
    public static final String executor = "executor";
    public static final String filter = "filter";
    public static final String func = "func";
    public static final String getter = "getter";
    public static final String handler = "handler";
    public static final String handlerClass = "handlerClass";
    public static final String idExtractor = "idExtractor";
    public static final String isDefaultIdTester = "isDefaultIdTester";
    public static final String isolationLevel = "isolationLevel";
    public static final String keyExtractor = "keyExtractor";
    public static final String mergeFunction = "mergeFunction";
    public static final String multimapSupplier = "multimapSupplier";
    public static final String n = "n";
    public static final String namedSql = "namedSql";
    public static final String offset = "offset";
    public static final String orElseAction = "orElseAction";
    public static final String parameterNames = "parameterNames";
    public static final String parameters = "parameters";
    public static final String parametersSetter = "parametersSetter";
    public static final String paramsSetter = "paramsSetter";
    public static final String propNamesToRefresh = "propNamesToRefresh";
    public static final String qualifier = "qualifier";
    public static final String register = "register";
    public static final String resultExtractor = "resultExtractor";
    public static final String resultExtractor1 = "resultExtractor1";
    public static final String resultExtractor2 = "resultExtractor2";
    public static final String resultExtractor3 = "resultExtractor3";
    public static final String resultSet = "resultSet"; // NOSONAR
    public static final String returnColumnIndexes = "returnColumnIndexes";
    public static final String returnColumnNames = "returnColumnNames";
    public static final String rowConsumer = "rowConsumer";
    public static final String rowExtractor = "rowExtractor";
    public static final String rowFilter = "rowFilter";
    public static final String rowMapper = "rowMapper";
    public static final String rowMapper1 = "rowMapper1";
    public static final String rowMapper2 = "rowMapper2";
    public static final String rowMapper3 = "rowMapper3";
    public static final String sql = "sql";
    public static final String sqlAction = "sqlAction";
    public static final String sqlAction1 = "sqlAction1";
    public static final String sqlAction2 = "sqlAction2";
    public static final String sqlAction3 = "sqlAction3";
    public static final String stmt = "stmt";
    public static final String stmtCreator = "stmtCreator";
    public static final String stmtSetter = "stmtSetter";
    public static final String supplier = "supplier";
    public static final String targetClass = "targetClass";
    public static final String targetType = "targetType";
    public static final String type = "type";
    public static final String uniquePropNamesForQuery = "uniquePropNamesForQuery";
    public static final String url = "url";
    public static final String valueExtractor = "valueExtractor";
}
