/*
 * Copyright (c) 2025, Haiyang Li.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.landawn.abacus.jdbc;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import com.landawn.abacus.TestBase;

@Tag("2025")
public class csTest extends TestBase {

    // Test all constant fields exist and have expected values

    @Test
    public void testResultSetConstant() {
        assertEquals("ResultSet", cs.ResultSet);
        assertNotNull(cs.ResultSet);
    }

    @Test
    public void testActionConstant() {
        assertEquals("action", cs.action);
    }

    @Test
    public void testAfterInvokeActionConstant() {
        assertEquals("afterInvokeAction", cs.afterInvokeAction);
    }

    @Test
    public void testAutoGeneratedKeyExtractorConstant() {
        assertEquals("autoGeneratedKeyExtractor", cs.autoGeneratedKeyExtractor);
    }

    @Test
    public void testBatchParametersConstant() {
        assertEquals("batchParameters", cs.batchParameters);
    }

    @Test
    public void testBatchSizeConstant() {
        assertEquals("batchSize", cs.batchSize);
    }

    @Test
    public void testBeforeInvokeActionConstant() {
        assertEquals("beforeInvokeAction", cs.beforeInvokeAction);
    }

    @Test
    public void testCloseHandlerConstant() {
        assertEquals("closeHandler", cs.closeHandler);
    }

    @Test
    public void testCmdConstant() {
        assertEquals("cmd", cs.cmd);
    }

    @Test
    public void testColumnGetterConstant() {
        assertEquals("columnGetter", cs.columnGetter);
    }

    @Test
    public void testColumnIndexConstant() {
        assertEquals("columnIndex", cs.columnIndex);
    }

    @Test
    public void testColumnNameConstant() {
        assertEquals("columnName", cs.columnName);
    }

    @Test
    public void testCondConstant() {
        assertEquals("cond", cs.cond);
    }

    @Test
    public void testConnConstant() {
        assertEquals("conn", cs.conn);
    }

    @Test
    public void testConsumerConstant() {
        assertEquals("consumer", cs.consumer);
    }

    @Test
    public void testConsumerForAllConstant() {
        assertEquals("consumerForAll", cs.consumerForAll);
    }

    @Test
    public void testCountConstant() {
        assertEquals("count", cs.count);
    }

    @Test
    public void testDaoInterfaceConstant() {
        assertEquals("daoInterface", cs.daoInterface);
    }

    @Test
    public void testDataSourceConstant() {
        assertEquals("dataSource", cs.dataSource);
    }

    @Test
    public void testDefaultColumnGetterConstant() {
        assertEquals("defaultColumnGetter", cs.defaultColumnGetter);
    }

    @Test
    public void testDownstreamConstant() {
        assertEquals("downstream", cs.downstream);
    }

    @Test
    public void testEntityConstant() {
        assertEquals("entity", cs.entity);
    }

    @Test
    public void testEntityClassConstant() {
        assertEquals("entityClass", cs.entityClass);
    }

    @Test
    public void testExecutorConstant() {
        assertEquals("executor", cs.executor);
    }

    @Test
    public void testFilterConstant() {
        assertEquals("filter", cs.filter);
    }

    @Test
    public void testFuncConstant() {
        assertEquals("func", cs.func);
    }

    @Test
    public void testGetterConstant() {
        assertEquals("getter", cs.getter);
    }

    @Test
    public void testHandlerConstant() {
        assertEquals("handler", cs.handler);
    }

    @Test
    public void testHandlerClassConstant() {
        assertEquals("handlerClass", cs.handlerClass);
    }

    @Test
    public void testIdExtractorConstant() {
        assertEquals("idExtractor", cs.idExtractor);
    }

    @Test
    public void testIsDefaultIdTesterConstant() {
        assertEquals("isDefaultIdTester", cs.isDefaultIdTester);
    }

    @Test
    public void testIsolationLevelConstant() {
        assertEquals("isolationLevel", cs.isolationLevel);
    }

    @Test
    public void testKeyExtractorConstant() {
        assertEquals("keyExtractor", cs.keyExtractor);
    }

    @Test
    public void testMergeFunctionConstant() {
        assertEquals("mergeFunction", cs.mergeFunction);
    }

    @Test
    public void testMultimapSupplierConstant() {
        assertEquals("multimapSupplier", cs.multimapSupplier);
    }

    @Test
    public void testNConstant() {
        assertEquals("n", cs.n);
    }

    @Test
    public void testNamedSqlConstant() {
        assertEquals("namedSql", cs.namedSql);
    }

    @Test
    public void testOffsetConstant() {
        assertEquals("offset", cs.offset);
    }

    @Test
    public void testOrElseActionConstant() {
        assertEquals("orElseAction", cs.orElseAction);
    }

    @Test
    public void testParameterNamesConstant() {
        assertEquals("parameterNames", cs.parameterNames);
    }

    @Test
    public void testParametersConstant() {
        assertEquals("parameters", cs.parameters);
    }

    @Test
    public void testParametersSetterConstant() {
        assertEquals("parametersSetter", cs.parametersSetter);
    }

    @Test
    public void testPropNamesToRefreshConstant() {
        assertEquals("propNamesToRefresh", cs.propNamesToRefresh);
    }

    @Test
    public void testQualifierConstant() {
        assertEquals("qualifier", cs.qualifier);
    }

    @Test
    public void testRegisterConstant() {
        assertEquals("register", cs.register);
    }

    @Test
    public void testResultExtractorConstant() {
        assertEquals("resultExtractor", cs.resultExtractor);
    }

    @Test
    public void testResultExtractor1Constant() {
        assertEquals("resultExtractor1", cs.resultExtractor1);
    }

    @Test
    public void testResultExtractor2Constant() {
        assertEquals("resultExtractor2", cs.resultExtractor2);
    }

    @Test
    public void testResultExtractor3Constant() {
        assertEquals("resultExtractor3", cs.resultExtractor3);
    }

    @Test
    public void testResultSetLowercaseConstant() {
        assertEquals("resultSet", cs.resultSet);
    }

    @Test
    public void testReturnColumnIndexesConstant() {
        assertEquals("returnColumnIndexes", cs.returnColumnIndexes);
    }

    @Test
    public void testReturnColumnNamesConstant() {
        assertEquals("returnColumnNames", cs.returnColumnNames);
    }

    @Test
    public void testRowConsumerConstant() {
        assertEquals("rowConsumer", cs.rowConsumer);
    }

    @Test
    public void testRowExtractorConstant() {
        assertEquals("rowExtractor", cs.rowExtractor);
    }

    @Test
    public void testRowFilterConstant() {
        assertEquals("rowFilter", cs.rowFilter);
    }

    @Test
    public void testRowMapperConstant() {
        assertEquals("rowMapper", cs.rowMapper);
    }

    @Test
    public void testRowMapper1Constant() {
        assertEquals("rowMapper1", cs.rowMapper1);
    }

    @Test
    public void testRowMapper2Constant() {
        assertEquals("rowMapper2", cs.rowMapper2);
    }

    @Test
    public void testRowMapper3Constant() {
        assertEquals("rowMapper3", cs.rowMapper3);
    }

    @Test
    public void testSqlConstant() {
        assertEquals("sql", cs.sql);
    }

    @Test
    public void testSqlActionConstant() {
        assertEquals("sqlAction", cs.sqlAction);
    }

    @Test
    public void testSqlAction1Constant() {
        assertEquals("sqlAction1", cs.sqlAction1);
    }

    @Test
    public void testSqlAction2Constant() {
        assertEquals("sqlAction2", cs.sqlAction2);
    }

    @Test
    public void testSqlAction3Constant() {
        assertEquals("sqlAction3", cs.sqlAction3);
    }

    @Test
    public void testStmtConstant() {
        assertEquals("stmt", cs.stmt);
    }

    @Test
    public void testStmtCreatorConstant() {
        assertEquals("stmtCreator", cs.stmtCreator);
    }

    @Test
    public void testStmtSetterConstant() {
        assertEquals("stmtSetter", cs.stmtSetter);
    }

    @Test
    public void testSupplierConstant() {
        assertEquals("supplier", cs.supplier);
    }

    @Test
    public void testTargetClassConstant() {
        assertEquals("targetClass", cs.targetClass);
    }

    @Test
    public void testTargetTypeConstant() {
        assertEquals("targetType", cs.targetType);
    }

    @Test
    public void testTypeConstant() {
        assertEquals("type", cs.type);
    }

    @Test
    public void testUniquePropNamesForQueryConstant() {
        assertEquals("uniquePropNamesForQuery", cs.uniquePropNamesForQuery);
    }

    @Test
    public void testUrlConstant() {
        assertEquals("url", cs.url);
    }

    @Test
    public void testValueExtractorConstant() {
        assertEquals("valueExtractor", cs.valueExtractor);
    }

    @Test
    public void testSelectPropNameConstant() {
        assertEquals("selectPropName", cs.selectPropName);
    }

    @Test
    public void testTargetValueTypeConstant() {
        assertEquals("targetValueType", cs.targetValueType);
    }

    @Test
    public void testIdConstant() {
        assertEquals("id", cs.id);
    }

    @Test
    public void testPropNamesToInsertConstant() {
        assertEquals("propNamesToInsert", cs.propNamesToInsert);
    }

    @Test
    public void testPropNamesToSaveConstant() {
        assertEquals("propNamesToSave", cs.propNamesToSave);
    }

    @Test
    public void testPropNamesToUpdateConstant() {
        assertEquals("propNamesToUpdate", cs.propNamesToUpdate);
    }

    @Test
    public void testPropsToUpdateConstant() {
        assertEquals("propsToUpdate", cs.propsToUpdate);
    }

    @Test
    public void testNamedInsertSqlConstant() {
        assertEquals("namedInsertSql", cs.namedInsertSql);
    }

    @Test
    public void testJoinEntityPropNameConstant() {
        assertEquals("joinEntityPropName", cs.joinEntityPropName);
    }

}
