/*
 * Copyright (c) 2021, Haiyang Li.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.landawn.abacus.jdbc.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a {@code static final String} field (typically inside a DAO interface's nested helper class)
 * as an embeddable SQL script that can be referenced by {@code @Query(id = "...")}.
 *
 * <p><b>Primary purposes:</b></p>
 * <ul>
 *   <li>Separate complex SQL from method-level annotations for improved readability.</li>
 *   <li>Allow SQL generated by a builder (e.g., {@code PSC.selectFrom(...).sql()}).</li>
 *   <li>Support use of Java text blocks for multi-line SQL formatting.</li>
 * </ul>
 *
 * <p><b>Usage Examples:</b></p>
 * <pre>{@code
 * public interface UserDao extends CrudDao<User, Long, SQLBuilder.PSC, UserDao>,
 *                                  JoinEntityHelper<User, SQLBuilder.PSC, UserDao> {
 *
 *     @Query(id = "listUserWithBiggerId")
 *     Set<User> listUserWithBiggerIdToSet(int id) throws SQLException;
 *
 *     @Query(id = "listActiveUsersWithOrders")
 *     List<User> listActiveUsersWithOrders(Bind("startDate") String startDate, Bind("minAmount") double minAmount) throws SQLException;
 *
 *     static final class SqlTable {
 *
 *         @SqlField
 *         static final String listUserWithBiggerId =
 *                 PSC.selectFrom(User.class)
 *                    .where(CF.gt("id"))
 *                    .sql();
 *
 *         // Complex SQL query defined using a Java text block:
 *         @SqlField
 *         static final String listActiveUsersWithOrders = """
 *             SELECT u.id,
 *                    u.name,
 *                    u.email,
 *                    u.status,
 *                    o.order_id,
 *                    o.total_amount,
 *                    o.created_at
 *             FROM users u
 *             JOIN orders o ON u.id = o.user_id
 *             WHERE u.status = 'ACTIVE'
 *               AND o.created_at >= :startDate
 *               AND o.total_amount >= :minAmount
 *             ORDER BY o.created_at DESC
 *             LIMIT 100
 *             """;
 *     }
 * }
 * }</pre>
 *
 * @see Query
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface SqlField {

    /**
     * Supplies an optional identifier that overrides the annotated field name when the SQL is
     * registered. When left empty the declaration name (for example {@code sql_listUserWithBiggerId}) becomes
     * the key, but setting a custom id makes it possible to share the same SQL across differently
     * named constants or shorten the token referenced from {@link Query}.
     *
     * <p><b>Usage Examples:</b></p>
     * <pre>{@code
     * @SqlField(id = "sql_listUserWithBiggerId")
     * static final String listUserWithBiggerId =
     *         PSC.selectFrom(User.class).where(CF.gt("id")).sql();
     * }</pre>
     *
     * @return the identifier used to reference the SQL when invoking {@link Query#id()}, Actual field name is used when it's empty.
     */
    String id() default ""; // default will be field name.
}
